name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip3 install -U catkin_pkg colcon-common-extensions vcstool numpy netifaces lark==1.1.1

      - name: Build ROS 2 on macOS
        run: |
          mkdir src
          vcs import src < ros2.repos
          colcon build --symlink-install --cmake-args -DBUILD_TESTING=OFF -DTHIRDPARTY=FORCE

      - name: ros2 doctor
        run: |
          source install/setup.zsh
          ros2 doctor
